name:                hello-world
version:             0.1.0.0
github:              "ProCrust/hello-world"
license:             BSD3
author:              "Kent Joash Zamudio"
maintainer:          "zamudiokentjoash@gmail.com"
copyright:           "Zamudio 2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ProCrust/hello-world#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hello-world-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-world

tests:
  hello-world-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-world
